name: detect_it
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter
    firebase_core: ^3.11.0
    cloud_firestore: ^5.6.3
    dartz: ^0.10.1
    image_picker: ^1.1.2
    go_router: ^14.8.0
    get_storage: ^2.1.1
    dio: ^5.8.0+1
    get: ^4.7.2
    themed: ^8.1.0
    equatable: ^2.0.7
    logger: ^2.0.0
    flutter_easyloading: ^3.0.5
    firebase_auth: ^5.4.2
    firebase_storage: ^12.4.2
    flutter_dotenv: ^5.2.1
    google_fonts: ^6.2.1
    flutter_launcher_icons: ^0.14.3
    google_sign_in: ^6.3.0
    flutter_svg: ^2.0.17
    adaptive_dialog: ^2.4.1
    cached_network_image: ^3.4.1
    phosphor_flutter: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    flutter_native_splash: ^2.4.4

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/images/
        - assets/icons/
        - assets/svg/
